server:
  port: 8092
  servlet:
    context-path: /phone-contact-system


spring:
  datasource:
    url: jdbc:h2:~/contact
    username: sa
    password:
    hikari:
      maximum-pool-size: 5
    driver-class-name: org.h2.Driver
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      path: /h2-ui
  main:
    allow-bean-definition-overriding: true

app:
  name: phone-contact-system
  version: 1
  description: Recruitment task for trygrupp


logging:
  level:
    org:
      springframework:
        retry: DEBUG
